---
- name: 'Update server'
  hosts: default
  become: true

  tasks:
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade all packages
      apt: upgrade=dist force_apt_get=yes